name: food_app
description: flutter project name is foodapp

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ">=0.14.0"
  flutter_sms: ^2.3.1
  firebase_core: ^1.4.0
  firebase_storage: ^8.0.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_analytics: ^8.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/categories/
    - assets/images/Foods/Snacks/
    - assets/images/Foods/FastFood/
    - assets/images/Foods/Noodlies/
    - assets/images/Foods/Vegetarian/
    - assets/images/Foods/Burger/
    - assets/images/Foods/Icecream/
    - assets/images/Foods/Bread/
    - assets/images/Foods/Coffe/
    - assets/images/Foods/Cake/
    - assets/images/Foods/Sandwitch/
    - assets/images/menu/
  fonts:
    - family: chewy
      fonts:
        - asset: assets/fonts/chewy.ttf
          weight: 700